### ISSUE TITLE
Category methods on UIView are not prefixed/suffixed

### ISSUE THREAD

**Issue by cbowns** [nicklockwood/ViewUtils#5]
Apple's documentation [recommends](https://developer.apple.com/library/ios/documentation/cocoa/conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4) using a prefix or suffix on all category methods to avoid unknowingly clashing with an existing or future method implementation by the framework that shares the same name.

ViewUtils should add a prefix or suffix to avoid this problem. More reading:
- How to know when your category has replaced an existing implementation: http://blog.clickablebliss.com/2010/01/19/finding-colliding-category-methods/
- Categories: general info. http://blog.bignerdranch.com/304-category-pros-and-cons/
- Dave DeLong's suffix recommendation: https://twitter.com/davedelong/status/175233959486164993

**Comment by nicklockwood** [comment]
I am aware of this recommendation but I don't fully agree with it.

My take is that incidental or private use of categories should be prefixed, but when (as in this case) your library _is_ a category, and the methods are all part of your public interface then the chance of collisions is low.

The purpose of ViewUtils is to provide an elegant extension of UIView's existing methods that are syntactically similar to the existing API. If anyone uses ViewUtils in a project it should be with full knowledge of the methods that it adds. If they use another similar library that clashes, it will be easy for them to detect and fix (it's also likely that should there be any method clashes, the implementation and function of both methods will be the same, so it won't matter).

Happy to discuss this further, either here or on Twitter.

**Comment by cbowns** [comment]
Ok. I still think categories should always always be prefixed or suffixed away from any potential clashes. Feel free to close this as not to be fixed.
