### ISSUE TITLE
Crashes on 64 bit iPhone 5s

### ISSUE THREAD

**Issue by omergul** [nicklockwood/ViewUtils#6]
Hi, I think there is a problem with 64 bit iPhone 5s platform. It crashes like saying Unrecognized selector sent to instance [uibutton top] as en example. What could be the problem?

**Comment by chasseurmic** [comment]
I have the same problem. My app sometimes crashes when the NIB is retrieved from the cache in `+ (id)instanceWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)bundleOrNil owner:(id)owner`:

``` objc
UINib *nib = [nibCache objectForKey:pathKey];
...
if (nib)
    {
        //attempt to load from nib
        NSArray *contents = [nib instantiateWithOwner:owner options:nil];
        UIView *view = [contents count]? [contents objectAtIndex:0]: nil;
        NSAssert ([view isKindOfClass:self], @"First object in nib '%@' was '%@'. Expected '%@'", nibName, view, self);
        return view;
    }
```

Any ideas?
